// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyliteCalendar.Data;

#nullable disable

namespace SkyliteCalendar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SkyliteCalendar.Models.Department", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ColorHex").IsRequired().HasDefaultValue("#185FA5").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Departments");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("FullName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                b.Property<int?>("DepartmentId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("DepartmentId");
                b.ToTable("Users");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.Meeting", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("StartTime").HasColumnType("TEXT");
                b.Property<DateTime>("EndTime").HasColumnType("TEXT");
                b.Property<int?>("DepartmentId").HasColumnType("INTEGER");
                b.Property<int>("CreatedByUserId").HasColumnType("INTEGER");
                b.Property<string?>("ExternalAttendees").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DepartmentId");
                b.HasIndex("CreatedByUserId");
                b.ToTable("Meetings");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.MeetingAttendee", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("MeetingId").HasColumnType("INTEGER");
                b.Property<int>("UserId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("MeetingId");
                b.HasIndex("UserId");
                b.ToTable("MeetingAttendees");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.User", b =>
            {
                b.HasOne("SkyliteCalendar.Models.Department", "Department")
                    .WithMany("Users").HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Department");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.Meeting", b =>
            {
                b.HasOne("SkyliteCalendar.Models.Department", "Department")
                    .WithMany("Meetings").HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("SkyliteCalendar.Models.User", "CreatedBy")
                    .WithMany().HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Department");
                b.Navigation("CreatedBy");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.MeetingAttendee", b =>
            {
                b.HasOne("SkyliteCalendar.Models.Meeting", "Meeting")
                    .WithMany("Attendees").HasForeignKey("MeetingId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("SkyliteCalendar.Models.User", "User")
                    .WithMany("MeetingAttendees").HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Meeting");
                b.Navigation("User");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.Department", b =>
            {
                b.Navigation("Users");
                b.Navigation("Meetings");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.Meeting", b =>
            {
                b.Navigation("Attendees");
            });

            modelBuilder.Entity("SkyliteCalendar.Models.User", b =>
            {
                b.Navigation("MeetingAttendees");
            });
#pragma warning restore 612, 618
        }
    }
}
